In [1033]:
pip install missingno

Requirement already satisfied: missingno in /opt/homebrew/lib/python3.11/site-packages (0.5.2)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (from missingno) (1.26.1)
Requirement already satisfied: matplotlib in /opt/homebrew/lib/python3.11/site-packages (from missingno) (3.8.2)
Requirement already satisfied: scipy in /opt/homebrew/lib/python3.11/site-packages (from missingno) (1.11.3)
Requirement already satisfied: seaborn in /opt/homebrew/lib/python3.11/site-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (23.2)
Requirement already satisfied: pillow>=8 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/lib/python3.11/site-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: pandas>=1.2 in /opt/homebrew/lib/python3.11/site-packages (from seaborn->missingno) (2.1.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.2->seaborn->missingno) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.2->seaborn->missingno) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1034]:
pip install plotly

Requirement already satisfied: plotly in /opt/homebrew/lib/python3.11/site-packages (5.22.0)
Requirement already satisfied: tenacity>=6.2.0 in /opt/homebrew/lib/python3.11/site-packages (from plotly) (8.3.0)
Requirement already satisfied: packaging in /opt/homebrew/lib/python3.11/site-packages (from plotly) (23.2)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1035]:
import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt
import re
import plotly.express as px
import seaborn as sns

domain_properties=pd.read_csv('domain_properties.csv',header=0)
# domain_properties=pd.read_csv('Sydney Suburbs Reviews.csv',header=0)

In [1036]:
domain_properties

,price,date_sold,suburb,num_bath,num_bed,num_parking,property_size,type,suburb_population,suburb_median_income,suburb_sqkm,suburb_lat,suburb_lng,suburb_elevation,cash_rate,property_inflation_index,km_from_cbd
0,530000,13/1/16,Kincumber,4,4,2,1351,House,7093,29432,9.914,-33.47252,151.40208,24,2.0,150.9,47.05
1,525000,13/1/16,Halekulani,2,4,2,594,House,2538,24752,1.397,-33.21772,151.55237,23,2.0,150.9,78.54
2,480000,13/1/16,Chittaway Bay,2,4,2,468,House,2028,31668,1.116,-33.32678,151.44557,3,2.0,150.9,63.59
3,452000,13/1/16,Leumeah,1,3,1,344,House,9835,32292,4.055,-34.05375,150.83957,81,2.0,150.9,40.12
4,365500,13/1/16,North Avoca,0,0,0,1850,Vacant land,2200,45084,1.497,-33.45608,151.43598,18,2.0,150.9,49.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11155,1900000,31/12/21,Kellyville,3,4,2,540,House,27971,46228,18.645,-33.69583,150.95622,78,0.1,220.1,30.08
11156,1300000,31/12/21,Seven Hills,3,7,2,1208,House,19326,33540,9.629,-33.77743,150.94272,38,0.1,220.1,26.58
11157,1025000,31/12/21,Sydney,2,2,1,129,Apartment / Unit / Flat,17252,35412,2.940,-33.86794,151.20998,65,0.1,220.1,0.31
11158,1087500,1/1/22,Prestons,2,4,2,384,House,15313,36244,9.215,-33.94155,150.87334,28,0.1,220.1,32.26
11159,1000000,1/1/22,Ourimbah,2,3,2,667,House,3951,37180,87.154,-33.31517,151.32611,191,0.1,220.1,61.95

In [1037]:
domain_properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11160 entries, 0 to 11159
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   price                     11160 non-null  int64
 1   date_sold                 11160 non-null  object
 2   suburb                    11160 non-null  object
 3   num_bath                  11160 non-null  int64
 4   num_bed                   11160 non-null  int64
 5   num_parking               11160 non-null  int64
 6   property_size             11160 non-null  int64
 7   type                      11160 non-null  object
 8   suburb_population         11160 non-null  int64
 9   suburb_median_income      11160 non-null  int64
 10  suburb_sqkm               11160 non-null  float64
 11  suburb_lat                11160 non-null  float64
 12  suburb_lng                11160 non-null  float64
 13  suburb_elevation          11160 non-null  int64
 14  cash_rate                 11160 non-null  float64
 15  property_inflation_index  11160 non-null  float64
 16  km_from_cbd               11160 non-null  float64
dtypes: float64(6), int64(8), object(3)
memory usage: 1.4+ MB

In [1038]:
domain_properties.isnull()

,price,date_sold,suburb,num_bath,num_bed,num_parking,property_size,type,suburb_population,suburb_median_income,suburb_sqkm,suburb_lat,suburb_lng,suburb_elevation,cash_rate,property_inflation_index,km_from_cbd
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11155,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11156,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11157,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11158,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11159,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1039]:
unique_suburbs_count = domain_properties['suburb'].nunique()
unique_suburbs_count

637

In [1040]:
unique_suburbs_count = domain_properties['type'].nunique()
unique_suburbs_count

16

In [1041]:
domain_properties['num_bath'].max()

46

In [1042]:
domain_properties['num_bed'].min()

0

In [1043]:
domain_properties['num_bed'].max()

47

In [1044]:
domain_properties['num_parking'].min()

0

In [1045]:
domain_properties['type'].value_counts()

type
House                            9583
Apartment / Unit / Flat           688
Townhouse                         211
Semi-Detached                     170
Vacant land                       163
Villa                             114
Duplex                             67
Terrace                            63
Block of Units                     37
Acreage / Semi-Rural               21
New House & Land                   15
New Apartments / Off the Plan       9
Development Site                    7
Studio                              5
Rural                               4
New land                            3
Name: count, dtype: int64

## We need to convert the non-numeric data type into numeric (type, suburb, date_sold)

In [1046]:
domain_properties['date_sold'] = pd.to_datetime(domain_properties['date_sold'])
domain_properties['year_sold'] = domain_properties['date_sold'].dt.year
domain_properties.drop('date_sold', axis=1, inplace=True)

/var/folders/hn/mcytwrsx2d565y97htgm6_8w0000gn/T/ipykernel_86941/3462621749.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  domain_properties['date_sold'] = pd.to_datetime(domain_properties['date_sold'])

In [1047]:
domain_properties

,price,suburb,num_bath,num_bed,num_parking,property_size,type,suburb_population,suburb_median_income,suburb_sqkm,suburb_lat,suburb_lng,suburb_elevation,cash_rate,property_inflation_index,km_from_cbd,year_sold
0,530000,Kincumber,4,4,2,1351,House,7093,29432,9.914,-33.47252,151.40208,24,2.0,150.9,47.05,2016
1,525000,Halekulani,2,4,2,594,House,2538,24752,1.397,-33.21772,151.55237,23,2.0,150.9,78.54,2016
2,480000,Chittaway Bay,2,4,2,468,House,2028,31668,1.116,-33.32678,151.44557,3,2.0,150.9,63.59,2016
3,452000,Leumeah,1,3,1,344,House,9835,32292,4.055,-34.05375,150.83957,81,2.0,150.9,40.12,2016
4,365500,North Avoca,0,0,0,1850,Vacant land,2200,45084,1.497,-33.45608,151.43598,18,2.0,150.9,49.98,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11155,1900000,Kellyville,3,4,2,540,House,27971,46228,18.645,-33.69583,150.95622,78,0.1,220.1,30.08,2021
11156,1300000,Seven Hills,3,7,2,1208,House,19326,33540,9.629,-33.77743,150.94272,38,0.1,220.1,26.58,2021
11157,1025000,Sydney,2,2,1,129,Apartment / Unit / Flat,17252,35412,2.940,-33.86794,151.20998,65,0.1,220.1,0.31,2021
11158,1087500,Prestons,2,4,2,384,House,15313,36244,9.215,-33.94155,150.87334,28,0.1,220.1,32.26,2022
11159,1000000,Ourimbah,2,3,2,667,House,3951,37180,87.154,-33.31517,151.32611,191,0.1,220.1,61.95,2022

## Normalising Numerical Data

In [1048]:
import numpy as np
import matplotlib.pyplot as plt


domain_properties['num_bed'] = np.log1p(domain_properties['num_bed'])
domain_properties['num_bath'] = np.log1p(domain_properties['num_bath'])
domain_properties['suburb_population'] = np.log1p(domain_properties['suburb_population'])
domain_properties['num_parking'] = np.log1p(domain_properties['num_parking'])

## Categorical Data Correlation Between Price

In [1049]:
pip install category_encoders

Requirement already satisfied: category_encoders in /opt/homebrew/lib/python3.11/site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.26.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.3.2)
Requirement already satisfied: scipy>=1.0.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.11.3)
Requirement already satisfied: statsmodels>=0.9.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (0.14.2)
Requirement already satisfied: pandas>=1.0.5 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (2.1.2)
Requirement already satisfied: patsy>=0.5.1 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in /opt/homebrew/lib/python3.11/site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /opt/homebrew/lib/python3.11/site-packages (from statsmodels>=0.9.0->category_encoders) (23.2)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1050]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

df_corr = domain_properties.copy()

# Correctly encoding 'type'
df_corr['type_encoded'] = label_encoder.fit_transform(df_corr['type'])

# Correctly encoding 'suburb' and fixing the typo
df_corr['suburb_encoded'] = label_encoder.fit_transform(df_corr['suburb'])

In [1051]:
# Assuming 'price' is a column in your domain_properties DataFrame
categorical_features = df_corr[['type_encoded', 'suburb_encoded', 'year_sold','price']]

# Calculating correlation
corr = abs(categorical_features.corr())['price'].sort_values()

# Printing sorted correlation values
print(corr)

suburb_encoded    0.031153
type_encoded      0.039359
year_sold         0.225294
price             1.000000
Name: price, dtype: float64

## Numerical Data Correlation Between Price

In [1052]:
# Identify numeric columns by excluding non-numeric ones
numeric_cols = domain_properties.select_dtypes(include=['int64', 'float64']).columns

# Exclude specific categorical columns if they are still present
categorical_features = ['type', 'suburb']  # Update this list based on your actual categorical columns
numerical_features = domain_properties[numeric_cols].drop(categorical_features, axis=1, errors='ignore')

# Now, numerical_features should contain only numeric data
print(numerical_features.columns)

Index(['price', 'num_bath', 'num_bed', 'num_parking', 'property_size',
       'suburb_population', 'suburb_median_income', 'suburb_sqkm',
       'suburb_lat', 'suburb_lng', 'suburb_elevation', 'cash_rate',
       'property_inflation_index', 'km_from_cbd'],
      dtype='object')

In [1053]:
# Calculate the absolute correlation with 'price'
corr = abs(numerical_features.corr()['price'])

# Sort the correlation values
sorted_corr = corr.sort_values()

print(sorted_corr)

suburb_elevation            0.008412
suburb_population           0.082029
property_size               0.099212
suburb_lat                  0.109136
suburb_sqkm                 0.153286
num_parking                 0.177473
suburb_lng                  0.177976
property_inflation_index    0.229929
cash_rate                   0.236636
num_bed                     0.255648
num_bath                    0.347931
km_from_cbd                 0.358321
suburb_median_income        0.365452
price                       1.000000
Name: price, dtype: float64

## Feature Selection

In [1054]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score, KFold

In [1055]:
# numeric_features = ['num_bed', 'num_bath', 'km_from_cbd', 'num_parking', 'year_sold', 'suburb_median_income']
# categorical_features = ['type', 'suburb']

In [1056]:
# numeric_transformer = Pipeline(steps=[
#     ('imputer', SimpleImputer(strategy='median')),
#     ('scaler', StandardScaler())
# ])
# categorical_transformer = Pipeline(steps=[
#     ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
#     ('onehot', OneHotEncoder(handle_unknown='ignore'))
# ])

In [1057]:
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', numeric_transformer, numeric_features),
#         ('cat', categorical_transformer, categorical_features)
#     ])

In [1058]:
# # Combine preprocessing and model into a single pipeline
# model = Pipeline(steps=[
#     ('preprocessor', preprocessor),
#     ('regressor', RandomForestRegressor(random_state=42))
# ])

In [1059]:
# # Split the data
# X = domain_properties.drop('price', axis=1)
# y = domain_properties['price']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# from sklearn.linear_model import LinearRegression


# reg = LinearRegression()

# reg.fit(X_train, y_train)

In [1060]:
# # Fit the model
# model.fit(X_train, y_train)

In [1061]:
# # Evaluate the model using cross-validation
# cv = KFold(n_splits=5, random_state=42, shuffle=True)
# cv_scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='neg_mean_squared_error')

# print(f'Mean Squared Error from CV: {-cv_scores.mean()}')

In [1062]:
domain_properties = domain_properties[['num_bed', 'num_bath','km_from_cbd','num_parking','year_sold','suburb_median_income','price']]

In [1063]:
domain_properties.head()

,num_bed,num_bath,km_from_cbd,num_parking,year_sold,suburb_median_income,price
0,1.609438,1.609438,47.05,1.098612,2016,29432,530000
1,1.609438,1.098612,78.54,1.098612,2016,24752,525000
2,1.609438,1.098612,63.59,1.098612,2016,31668,480000
3,1.386294,0.693147,40.12,0.693147,2016,32292,452000
4,0.000000,0.000000,49.98,0.000000,2016,45084,365500

In [1064]:
# # library untuk preprocessing

# from sklearn.preprocessing import OneHotEncoder
# from sklearn.impute import SimpleImputer
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# import category_encoders as ce

# binary_encoder_pipeline = Pipeline([
#                                     ('imputer',SimpleImputer(strategy = 'constant',fill_value = 'NC')),
#                                     ('binary encoder',ce.BinaryEncoder())
# ])

# transformer= ColumnTransformer([('one_hot',OneHotEncoder(drop='first'),['type']),
#      ('binary encoder',binary_encoder_pipeline,['suburb']),
# ], remainder='passthrough')

# transformed_data = transformer.fit_transform(domain_properties)
# # Convert the transformed_data numpy array to a DataFrame
# transformed_df = pd.DataFrame(transformed_data, index=domain_properties.index)
# # Replace 'type' with the first column of transformed data
# domain_properties['type'] = transformed_df.iloc[:, 0]

# # Replace 'suburb' with the second column of transformed data
# domain_properties['suburb'] = transformed_df.iloc[:, 1]

In [1065]:
domain_properties

,num_bed,num_bath,km_from_cbd,num_parking,year_sold,suburb_median_income,price
0,1.609438,1.609438,47.05,1.098612,2016,29432,530000
1,1.609438,1.098612,78.54,1.098612,2016,24752,525000
2,1.609438,1.098612,63.59,1.098612,2016,31668,480000
3,1.386294,0.693147,40.12,0.693147,2016,32292,452000
4,0.000000,0.000000,49.98,0.000000,2016,45084,365500
...,...,...,...,...,...,...,...
11155,1.609438,1.386294,30.08,1.098612,2021,46228,1900000
11156,2.079442,1.386294,26.58,1.098612,2021,33540,1300000
11157,1.098612,1.098612,0.31,0.693147,2021,35412,1025000
11158,1.609438,1.098612,32.26,1.098612,2022,36244,1087500
11159,1.386294,1.098612,61.95,1.098612,2022,37180,1000000

In [1066]:
from sklearn.preprocessing import StandardScaler

# Split the data
X = domain_properties.drop('price', axis=1)
y = domain_properties['price']

scaler = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_s = scaler.fit_transform(X_train)

from sklearn.linear_model import LinearRegression


reg = LinearRegression()

reg.fit(X_train_s, y_train)

LinearRegression()

In [1067]:
X_test_s = scaler.transform(X_test)

In [1068]:
reg.score(X_test_s,y_test)

0.3802016745999526

In [1069]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor()

forest.fit(X_train_s, y_train)

RandomForestRegressor()

In [1070]:
forest.score(X_test_s,y_test)

0.6051567431703853

In [1071]:
from sklearn.model_selection import GridSearchCV

forest = RandomForestRegressor()

param_grid = {
    "n_estimators": [30, 50, 100],
    "max_features": [8, 12, 20],
}

grid_search = GridSearchCV(forest, param_grid, cv = 5, scoring="neg_mean_squared_error",return_train_score=True)

grid_search.fit(X_train_s,y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_features': [8, 12, 20],
                         'n_estimators': [30, 50, 100]},
             return_train_score=True, scoring='neg_mean_squared_error')

In [1072]:
best_forest = grid_search.best_estimator_

In [1073]:
best_forest.score(X_test_s, y_test)

0.5975368691637981

In [1074]:
import joblib

# Save your model
joblib.dump(best_forest, 'final_model.pkl')

['final_model.pkl']